// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4LGFMucCu-2x001i1sV8tiYjCDsfKqQ',
    appId: '1:740837220576:web:9409ef48c764526cff3085',
    messagingSenderId: '740837220576',
    projectId: 'tubes-flutter-eeefb',
    authDomain: 'tubes-flutter-eeefb.firebaseapp.com',
    storageBucket: 'tubes-flutter-eeefb.firebasestorage.app',
    measurementId: 'G-TBKEVW1DLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNmt5TnA-dRutFq69J40WgERo4ZO2K_G4',
    appId: '1:740837220576:android:0324225a36f73264ff3085',
    messagingSenderId: '740837220576',
    projectId: 'tubes-flutter-eeefb',
    storageBucket: 'tubes-flutter-eeefb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO4LGFMucCu-2x001i1sV8tiYjCDsfKqQ',
    appId: '1:740837220576:web:6c096f76451f7df4ff3085',
    messagingSenderId: '740837220576',
    projectId: 'tubes-flutter-eeefb',
    authDomain: 'tubes-flutter-eeefb.firebaseapp.com',
    storageBucket: 'tubes-flutter-eeefb.firebasestorage.app',
    measurementId: 'G-JLNQNE5ZEQ',
  );
}
